### PR TITLE
NPT-695: Delete any docker with nexus-cli is

### LINKED ISSUE #73: [Bug]: During installation getting error due to previously failed install.
### Contact Details

_No response_

### Tell us the project / group you are associated with

Community (Default)

### What happened?

Here is the output of the get-nexus-cli command

graph-framework-for-microservices-test> bash ./get-nexus-cli.sh
Error response from daemon: Conflict. The container name "/nexus-cli" is already in use by container "42dcae36b54f538aeb245e75c22e4572a16c47c924034707b5309fc0e4731eb5". You have to remove (or rename) that container to be able to reuse that name.

### Describe the expected behavior

_No response_

### What version are you running?

nexus was not installed yet.

### How critical is this bug to you?

Minor - non-functional bug

### How can we recreate the bug?

run the installation script twice.

### Any debug data that you are able to share?

n/a

### What is your operating system?

MacOS

### Any additional / relevant info

the problem is fixed by running 
docker rm nexus-cli

recommendation: the install script should be able to do this itself.

### PR DESCRIPTION
**Pull request by sankar17**
closes #73 

For any reason `bash get-nexus-cli.sh` failed, the next re-try might fail if the previous docker is running. So added a step to remove the docker before creating new docker with nexus-cli

### CODE REVIEW

**Review by ramramu3433 — APPROVED** [review]

File: cli/get-nexus-cli.sh [hunk 1]
```diff
@@ -62,6 +62,8 @@ docker_name="nexus-cli"
 darwin_src_path="/nexus/darwin/nexus"
 linux_src_path="/nexus/linux/nexus"
 
+docker rm -f ${docker_name} &> /dev/null
+
 docker pull ${REPOSITORY}:${VERSION} 1> /dev/null
 docker create --name "$docker_name" ${REPOSITORY}:${VERSION} 1> /dev/null
```
Comment (xmen4xp) [inline cli/get-nexus-cli.sh:68]: @sankar17 we may want to remove the docker image after cli is successfully downloaded ?

**Review by xmen4xp — CHANGES_REQUESTED** [review]

**Review by xmen4xp — APPROVED** [review]
